version: '2.4'
services:
  webserver:
    build: ./web
    ports:
      - "3000:80"
    links:
      - backend
    restart: always

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "3001:3000"
    links:
      - mongodb
    restart: always

  kafka:
    depends_on:
       - zookeeper
    image: wurstmeister/kafka:2.11-2.0.0
    expose:
      - "9092"
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
       - ./conf/kafka/config:/opt/kafka/config
       - ./data/kafka/logs:/tmp/kafka-logs
    environment:
      KAFKA_BROKER_ID: 0       
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_HEAP_OPTS: "-Xmx3G -Xms3G"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_JVM_PERFORMANCE_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      KAFKA_LOG_DIRS: /tmp/kafka-logs
    links:
      - mongodb
      - zookeeper
    restart: always
    mem_limit: 6G

  zookeeper:
    image: wurstmeister/zookeeper
    volumes:
        - ./data/zookeeper/data:/tmp/zookeeper
        - ./data/zookeeper/log:/var/log/zookeeper
    expose:
      - "2181"
      - "2888"
      - "3888"
    ports:
      - "2181:2181"
    restart: always
    mem_limit: 1024M

  mongodb:
    image: mongo:3.4.2
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db
    command: mongod --smallfiles --wiredTigerCacheSizeGB=2
    mem_limit: 4G
    restart: always

volumes:
  mongodb_volume:


